
sensor:
  - platform: sps30
    i2c_id: i2c_a
    address: ${sps30_addr}
    update_interval: ${sps30_update}
    idle_interval: ${sps30_idle}

    pm_1_0:
      name: "SPS30 PM1.0"
      id: sps30_pm_1_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_2_5:
      name: "SPS30 PM2.5"
      id: sps30_pm_2_5
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_4_0:
      name: "SPS30 PM4.0"
      id: sps30_pm_4_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_10_0:
      name: "SPS30 PM10"
      id: sps30_pm_10_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1
    # Unnecessary counts (i think)
    #pmc_0_5:
    #  name: "SPS30 PMC0.5"
    #  id: sps30_pmc_0_5
    #pmc_1_0:
    #  name: "SPS30 PMC1.0"
    #  id: sps30_pmc_1_0
    #pmc_2_5:
    #  name: "SPS30 PMC2.5"
    #  id: sps30_pmc_2_5
    #pmc_4_0:
    #  name: "SPS30 PMC4.0"
    #  id: sps30_pmc_4_0
    #pmc_10_0:
    #  name: "SPS30 PMC10"
    #  id: sps30_pmc_10_0

    pm_size:
      name: "SPS30 Typical Particle Size"
      id: sps30_pm_size



text_sensor:
  - platform: template
    name: "SPS30 PM2.5 Level"
    id: sps30_pm25_level
    update_interval: 5s
    lambda: |-
      float v = id(sps30_pm_2_5);
      if (isnan(v)) return std::string("Unknown");
      if (v <= 10) return std::string("Green");
      if (v <= 25) return std::string("Yellow");
      if (v <= 50) return std::string("Orange");
      return std::string("Red");

  - platform: template
    name: "SPS30 PM10 Level"
    id: sps30_pm10_level
    update_interval: 5s
    lambda: |-
      float v = id(sps30_pm_10_0);
      if (isnan(v)) return std::string("Unknown");
      if (v <= 40)  return std::string("Green");
      if (v <= 75)  return std::string("Yellow");
      if (v <= 150) return std::string("Orange");
      return std::string("Red");

  - platform: template
    name: "SPS30 PM1.0 Level"
    id: sps30_pm1_level
    update_interval: 5s
    lambda: |-
      float v = id(sps30_pm_1_0);
      if (isnan(v)) return std::string("Unknown");
      if (v <= 5)  return std::string("Green");
      if (v <= 10) return std::string("Yellow");
      if (v <= 20) return std::string("Orange");
      return std::string("Red");

  - platform: template
    name: "SPS30 PM Worst Level"
    id: sps30_pm_worst_level
    update_interval: 5s
    lambda: |-
      auto sev_pm25 = [](float v)->int {
        if (isnan(v)) return -1;
        if (v <= 10) return 0;
        if (v <= 25) return 1;
        if (v <= 50) return 2;
        return 3;
      };
      auto sev_pm10 = [](float v)->int {
        if (isnan(v)) return -1;
        if (v <= 40)  return 0;
        if (v <= 75)  return 1;
        if (v <= 150) return 2;
        return 3;
      };

      int worst = -1;
      worst = std::max(worst, sev_pm25(id(sps30_in_pm25_ugm3)));
      worst = std::max(worst, sev_pm10(id(sps30_in_pm10_ugm3)));

      if (worst < 0) return std::string("Unknown");
      if (worst == 0) return std::string("Green");
      if (worst == 1) return std::string("Yellow");
      if (worst == 2) return std::string("Orange");
      return std::string("Red");
