sensor:
  - platform: sps30
    i2c_id: i2c_a
    address: ${sps30_addr}
    update_interval: ${sps30_update}
    idle_interval: ${sps30_idle}

    pm_1_0:
      name: "SPS30 PM1.0"
      id: sps30_pm_1_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_2_5:
      name: "SPS30 PM2.5"
      id: sps30_pm_2_5
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_4_0:
      name: "SPS30 PM4.0"
      id: sps30_pm_4_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pm_10_0:
      name: "SPS30 PM10"
      id: sps30_pm_10_0
      filters:
        - sliding_window_moving_average:
            window_size: ${sps30_sma_window}
            send_every: 1

    pmc_0_5:
      name: "SPS30 PMC0.5"
      id: sps30_pmc_0_5
    pmc_1_0:
      name: "SPS30 PMC1.0"
      id: sps30_pmc_1_0
    pmc_2_5:
      name: "SPS30 PMC2.5"
      id: sps30_pmc_2_5
    pmc_4_0:
      name: "SPS30 PMC4.0"
      id: sps30_pmc_4_0
    pmc_10_0:
      name: "SPS30 PMC10"
      id: sps30_pmc_10_0

    pm_size:
      name: "SPS30 Typical Particle Size"
      id: sps30_pm_size
