api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  ap:
#    ssid: "${devicename}-fallback"
#    password: !secret ap_password
#
#captive_portal:
