substitutions:
  # LED capability
  led_pin: GPIO21

  # I2C A bus pins (leave frequency unset; SPS30 can be picky)
  i2c_a_sda: GPIO5
  i2c_a_scl: GPIO6

  # UART A pins (avoid uart0/1 naming entirely)
  uart_a_tx: GPIO43
  uart_a_rx: GPIO44
  uart_a_baud: "9600"

  # Device defaults
  sds011_update: 1min
  scd4x_update: 10s
  sps30_addr: "0x69"
  sps30_update: 10s
  sps30_idle: 5min
  sps30_sma_window: "6"

  # Optional display (SPI A) pins (set if you enable display packages)
  oled_address: "0x3C"
  oled_update: 1s
  oled_page_interval: 5s



  led_light_id: onboard_led
  pm_worst_level_id: sps30_pm_worst_level

font:
  - file: "gfonts://Roboto Mono"
    id: font_small
    size: 12

display:
  - platform: ssd1306_i2c
    id: oled
    address: ${oled_address}
    model: "SSD1306 128x64"
    update_interval: ${oled_update}
    pages:
      - id: page_pm
        lambda: |-
          it.printf(0, 0, id(font_small), "Hello world");
          it.printf(0, 16, id(font_small), "PM2.5: %.1f", id(sps30_pm_2_5).state);
          it.printf(0, 28, id(font_small), "PM10 : %.1f", id(sps30_pm_10_0).state);
          it.printf(0, 40, id(font_small), "SDS2.5: %.1f", id(sds011_pm_2_5).state);
          it.printf(0, 52, id(font_small), "SDS10 : %.1f", id(sds011_pm_10_0).state);

      - id: page_scd
        lambda: |-
          it.printf(0, 0, id(font_small), "Hello world");
          it.printf(0, 16, id(font_small), "CO2 : %.0f ppm", id(scd41_co2).state);
          it.printf(0, 28, id(font_small), "Temp: %.1f", id(scd41_temp).state);
          it.printf(0, 40, id(font_small), "Hum : %.1f%%", id(scd41_humidity).state);
          it.printf(0, 52, id(font_small), "PM1 : %.1f", id(sps30_pm_1_0).state);

interval:
  - interval: ${oled_page_interval}
    then:
      - display.page.show_next: oled
      - component.update: oled
packages:
  common_base: !include ../common/base.yaml
  common_status: !include ../common/status.yaml

  hw_led: !include ../hw/led_onboard.yaml
  hw_i2c_a: !include ../hw/i2c_a.yaml
  hw_uart_a: !include ../hw/uart_a.yaml

  dev_sps30: !include ../devices/sps30.yaml
  dev_scd4x: !include ../devices/scd4x.yaml
  dev_sds011: !include ../devices/sds011.yaml

  #feat_led_mode_select: !include ../features/led_mode_select.yaml
  #glue_led_mode_auto_pm: !include ../glue/led_mode_auto_pm.yaml
  # Will test managed updates later
  #feat_managed_update_on_boot: !include ../features/managed_update_on_boot.yaml


  # Will probably discard these later. 
  #feat_pm_levels: !include ../features/pm_levels.yaml
  #eat_led_status: !include ../features/pm_led_status.yaml

  #glue_pm_source_select: !include ../glue/pm_source_select.yaml
  #glue_levels_to_led: !include ../glue/pm_levels_to_led.yaml

  # ---- Optional LVGL display stack (enable as a group) ----
  # hw_spi_a: !include ../hw/spi_a.yaml
  # disp_driver: !include ../displays/display_gc9a01.yaml
  # feat_ui_lvgl: !include ../features/ui_lvgl.yaml
  # glue_pm_to_ui: !include ../glue/pm_to_ui.yaml


  # The MICS is a PAIN to calculate values from, and the values contain crosstalk across sensors.
  # Will revisit or abandon. 
  # mics6814: !include ../devices/mics6814.yaml
